"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEED_SOFTWARE_SYSTEMS = exports.SEED_ADMIN = void 0;
exports.runSeed = runSeed;
const client_1 = require("@prisma/client");
const bcryptjs_1 = __importDefault(require("bcryptjs"));
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const prisma = new client_1.PrismaClient();
exports.SEED_ADMIN = {
    email: process.env.ADMIN_EMAIL || 'admin@enterprise.internal',
    password: process.env.ADMIN_PASSWORD || 'Admin@123456',
    name: process.env.ADMIN_NAME || 'Enterprise System Administrator',
    role: 'ADMIN',
    department: 'Enterprise Architecture & Governance',
};
exports.SEED_SOFTWARE_SYSTEMS = [
    {
        systemId: 'SYS-HR-001',
        name: 'Enterprise HR Portal & Talent Suite',
        description: 'Centralized human resource management portal for employee lifecycle, benefits administration, onboarding workflows, and talent performance reviews.',
        businessDomain: 'HR',
        domainOwner: 'Sarah Jenkins',
        ownerEmail: 'sarah.jenkins@enterprise.internal',
        developmentTeam: 'People Tech Core Squad',
        technologyStack: 'React, Node.js, Express, PostgreSQL, Docker, AWS ECS',
        programmingLanguage: 'TypeScript',
        framework: 'React / Express',
        database: 'PostgreSQL 15',
        infrastructure: 'AWS ECS / Fargate',
        repositoryUrl: 'https://github.com/enterprise-org/hr-talent-suite',
        documentationUrl: 'https://wiki.enterprise.internal/display/HR/TalentSuite',
        environment: 'Production',
        status: 'Active',
        criticality: 'High',
        version: '3.4.2',
        deploymentDate: new Date('2023-04-15'),
        dependencies: 'Active Directory, Workday API, Corporate Slack Bot',
        securityNotes: 'Implements SSO via SAML 2.0 with MFA enforcement. Data encrypted at rest via AES-256.',
        complianceRequirements: 'GDPR, SOC 2 Type II, Equal Employment Opportunity (EEO) compliance',
        notes: 'Undergoing quarterly security audit; slated for mobile companion app integration in Q4.',
    },
    {
        systemId: 'SYS-CRM-002',
        name: 'Apex Global CRM Platform',
        description: 'Enterprise customer relationship management system tracking leads, client interactions, deal pipelines, customer contracts, and automated sales outreach.',
        businessDomain: 'Sales',
        domainOwner: 'Marcus Vance',
        ownerEmail: 'marcus.vance@enterprise.internal',
        developmentTeam: 'Revenue Engineering Team',
        technologyStack: 'Next.js, Go, PostgreSQL, Redis, Kubernetes, GCP',
        programmingLanguage: 'Go / TypeScript',
        framework: 'Next.js 14 / Gin Gonic',
        database: 'PostgreSQL 16 / Redis Cluster',
        infrastructure: 'Google Kubernetes Engine (GKE)',
        repositoryUrl: 'https://github.com/enterprise-org/apex-crm-core',
        documentationUrl: 'https://wiki.enterprise.internal/display/SALES/ApexCRM',
        environment: 'Production',
        status: 'Active',
        criticality: 'Critical',
        version: '4.1.0',
        deploymentDate: new Date('2022-11-20'),
        dependencies: 'Stripe Billing API, HubSpot Sync, Salesforce Connector, SendGrid',
        securityNotes: 'Zero-trust network model, TLS 1.3 enforced, OAuth2 with role-based scoping.',
        complianceRequirements: 'SOC 2 Type II, ISO 27001, CCPA, GDPR',
        notes: 'Mission-critical revenue system. 99.99% uptime SLA required.',
    },
    {
        systemId: 'SYS-FIN-003',
        name: 'LedgerCore Financial Reporting System',
        description: 'High-throughput financial ledger and statutory reporting engine generating balance sheets, tax compliance statements, and real-time cashflow analytics.',
        businessDomain: 'Finance',
        domainOwner: 'Elena Rostova',
        ownerEmail: 'elena.rostova@enterprise.internal',
        developmentTeam: 'FinTech Platform Squad',
        technologyStack: 'Angular, Java Spring Boot, PostgreSQL, Apache Kafka, Azure',
        programmingLanguage: 'Java 21 / TypeScript',
        framework: 'Spring Boot 3.2 / Angular 17',
        database: 'PostgreSQL 15 Enterprise Cluster',
        infrastructure: 'Microsoft Azure Kubernetes Service (AKS)',
        repositoryUrl: 'https://github.com/enterprise-org/ledger-core-fin',
        documentationUrl: 'https://wiki.enterprise.internal/display/FIN/LedgerCore',
        environment: 'Production',
        status: 'Active',
        criticality: 'Critical',
        version: '5.2.1',
        deploymentDate: new Date('2021-08-10'),
        dependencies: 'ERP Gateway, Swift Payment Network, Oracle Financials Bridge',
        securityNotes: 'Dual-approval required for sensitive transactions. Comprehensive tamper-evident immutable audit log.',
        complianceRequirements: 'SOX (Sarbanes-Oxley), PCI-DSS Level 1, IFRS Standards',
        notes: 'Handles end-of-month financial closing. Restricted read/write access enforced by VP Finance.',
    },
    {
        systemId: 'SYS-SCM-004',
        name: 'LogiTrack Supply Chain Management Engine',
        description: 'End-to-end logistics platform managing raw materials procurement, warehouse inventory tracking, supplier scorecards, and freight shipment dispatching.',
        businessDomain: 'Operations',
        domainOwner: 'David Chen',
        ownerEmail: 'david.chen@enterprise.internal',
        developmentTeam: 'Operations Logistics Devs',
        technologyStack: 'Vue.js, Python FastAPI, PostgreSQL, RabbitMQ, AWS',
        programmingLanguage: 'Python 3.11 / TypeScript',
        framework: 'FastAPI / Vue 3',
        database: 'PostgreSQL 15 / TimescaleDB',
        infrastructure: 'AWS Elastic Beanstalk & RDS',
        repositoryUrl: 'https://github.com/enterprise-org/logitrack-scm',
        documentationUrl: 'https://wiki.enterprise.internal/display/OPS/LogiTrack',
        environment: 'Production',
        status: 'Active',
        criticality: 'High',
        version: '2.8.0',
        deploymentDate: new Date('2023-01-18'),
        dependencies: 'FedEx Web Services, DHL API, SAP Logistics Connector, IoT GPS Trackers',
        securityNotes: 'API token rate limiting, Web Application Firewall (WAF) enabled.',
        complianceRequirements: 'ISO 9001, Customs-Trade Partnership Against Terrorism (C-TPAT)',
        notes: 'Connected to 14 regional distribution centers with real-time barcode scanning.',
    },
    {
        systemId: 'SYS-IT-005',
        name: 'OmniDesk Internal Helpdesk & IT Asset Manager',
        description: 'Corporate ticketing system, hardware/software asset inventory tracker, license allocation dashboard, and employee IT self-service request catalog.',
        businessDomain: 'IT',
        domainOwner: 'Michael Scott',
        ownerEmail: 'michael.scott@enterprise.internal',
        developmentTeam: 'Internal Enterprise Tools',
        technologyStack: 'React, Node.js, PostgreSQL, Redis, Docker, Azure',
        programmingLanguage: 'TypeScript',
        framework: 'React / Express',
        database: 'PostgreSQL 15',
        infrastructure: 'Azure Container Instances',
        repositoryUrl: 'https://github.com/enterprise-org/omnidesk-itsm',
        documentationUrl: 'https://wiki.enterprise.internal/display/IT/OmniDesk',
        environment: 'Production',
        status: 'Active',
        criticality: 'Medium',
        version: '2.3.4',
        deploymentDate: new Date('2022-06-01'),
        dependencies: 'Okta Identity Provider, Jamf Pro MDM, Jira Software Integration',
        securityNotes: 'Strict RBAC separating Helpdesk Technicians from System Admins.',
        complianceRequirements: 'ITIL v4 Framework Guidelines, SOC 2',
        notes: 'Average ticket resolution time currently 4.2 hours.',
    },
    {
        systemId: 'SYS-PAY-006',
        name: 'PayStream Enterprise Payroll Engine',
        description: 'Automated salary calculation, direct deposit routing, tax withholding deduction calculation, and benefits reconciliation platform.',
        businessDomain: 'Finance',
        domainOwner: 'Patricia Martinez',
        ownerEmail: 'patricia.martinez@enterprise.internal',
        developmentTeam: 'Compensation Tech Group',
        technologyStack: 'Java Spring Boot, PostgreSQL, AWS Lambda, HashiCorp Vault',
        programmingLanguage: 'Java 17',
        framework: 'Spring Boot 3.1',
        database: 'PostgreSQL 14 (Encrypted)',
        infrastructure: 'AWS ECS / Private Subnet VPC',
        repositoryUrl: 'https://github.com/enterprise-org/paystream-payroll',
        documentationUrl: 'https://wiki.enterprise.internal/display/FIN/PayStream',
        environment: 'Production',
        status: 'Under Maintenance',
        criticality: 'Critical',
        version: '3.1.5',
        deploymentDate: new Date('2022-03-30'),
        dependencies: 'Automated Clearing House (ACH) Gateway, IRS Electronic Tax Filing API',
        securityNotes: 'PII and banking account numbers encrypted with separate key envelopes stored in HashiCorp Vault.',
        complianceRequirements: 'IRS Publication 1075, NACHA Operating Rules, SOX 404',
        notes: 'Currently undergoing scheduled patch upgrade for fiscal year tax bracket recalculations.',
    },
    {
        systemId: 'SYS-DOC-007',
        name: 'VaultDocs Corporate Knowledge & Document Management',
        description: 'Enterprise document repository with semantic indexing, OCR text extraction, contract versioning, and compliance retention schedules.',
        businessDomain: 'Operations',
        domainOwner: 'Rachel Adams',
        ownerEmail: 'rachel.adams@enterprise.internal',
        developmentTeam: 'Information Governance Squad',
        technologyStack: 'Python Django, PostgreSQL, Elasticsearch, AWS S3, Redis',
        programmingLanguage: 'Python 3.11',
        framework: 'Django 4.2 / React',
        database: 'PostgreSQL 15 / Elasticsearch 8',
        infrastructure: 'AWS EKS / S3 Object Storage',
        repositoryUrl: 'https://github.com/enterprise-org/vaultdocs-dms',
        documentationUrl: 'https://wiki.enterprise.internal/display/OPS/VaultDocs',
        environment: 'Production',
        status: 'Active',
        criticality: 'Medium',
        version: '1.9.0',
        deploymentDate: new Date('2023-09-12'),
        dependencies: 'AWS Textract, Apache Tika, Office 365 Graph API',
        securityNotes: 'Watermarking applied on classified PDF exports. Full document access auditing.',
        complianceRequirements: 'ISO 27001, HIPAA (for HR health certificates)',
        notes: 'Indexed over 1.2 million confidential corporate documents.',
    },
    {
        systemId: 'SYS-MKT-008',
        name: 'CampaignHub Marketing Automation Suite',
        description: 'Omnichannel campaign orchestration, lead scoring, newsletter distribution, social media scheduling, and conversion analytics.',
        businessDomain: 'Marketing',
        domainOwner: 'Liam Gallagher',
        ownerEmail: 'liam.gallagher@enterprise.internal',
        developmentTeam: 'Growth Marketing Engineering',
        technologyStack: 'React, Node.js, PostgreSQL, Redis, SendGrid, GCP',
        programmingLanguage: 'TypeScript',
        framework: 'React / NestJS',
        database: 'PostgreSQL 15',
        infrastructure: 'Google Cloud Run',
        repositoryUrl: 'https://github.com/enterprise-org/campaign-hub',
        documentationUrl: 'https://wiki.enterprise.internal/display/MKT/CampaignHub',
        environment: 'Production',
        status: 'Active',
        criticality: 'Low',
        version: '2.1.0',
        deploymentDate: new Date('2023-05-14'),
        dependencies: 'Twilio SMS, Google Analytics 4, Meta Marketing API, LinkedIn Ads API',
        securityNotes: 'Unsubscribe requests honored instantaneously with automated opt-out blacklist sync.',
        complianceRequirements: 'CAN-SPAM Act, CASL, GDPR Cookie & Consent Guidelines',
        notes: 'Handles up to 500,000 outgoing campaign emails per week.',
    },
    {
        systemId: 'SYS-CS-009',
        name: 'SupportPulse Customer Escalation Portal',
        description: 'Real-time customer support desk with omnichannel chat routing, SLA timer tracking, customer sentiment scoring, and executive escalation workflows.',
        businessDomain: 'Customer Service',
        domainOwner: 'Jessica Taylor',
        ownerEmail: 'jessica.taylor@enterprise.internal',
        developmentTeam: 'Customer Experience Squad',
        technologyStack: 'React, Node.js, WebSockets, PostgreSQL, Redis, Docker',
        programmingLanguage: 'TypeScript',
        framework: 'React 18 / Express / Socket.io',
        database: 'PostgreSQL 15 / Redis',
        infrastructure: 'AWS ECS / CloudFront',
        repositoryUrl: 'https://github.com/enterprise-org/support-pulse',
        documentationUrl: 'https://wiki.enterprise.internal/display/CS/SupportPulse',
        environment: 'Production',
        status: 'Active',
        criticality: 'High',
        version: '3.0.4',
        deploymentDate: new Date('2023-02-28'),
        dependencies: 'Zendesk Bridge, VoIP Phone Gateway, AI Sentiment Classifier API',
        securityNotes: 'End-to-end encrypted chat logs. Customer credit card numbers automatically redacted.',
        complianceRequirements: 'SOC 2, ISO 27001, CCPA',
        notes: 'Maintains an average Customer Satisfaction (CSAT) rating of 94.6%.',
    },
    {
        systemId: 'SYS-ATT-010',
        name: 'BioClock Legacy Employee Attendance Tracker',
        description: 'Legacy on-premise attendance punch-card tracking and biometric badge reader interface. Slated for decommissioning in favor of HR Talent Suite.',
        businessDomain: 'HR',
        domainOwner: 'Andrew Wilson',
        ownerEmail: 'andrew.wilson@enterprise.internal',
        developmentTeam: 'Legacy Support Group',
        technologyStack: 'ASP.NET Core, C#, PostgreSQL, Windows Server, IIS',
        programmingLanguage: 'C# (.NET 6)',
        framework: 'ASP.NET Core MVC',
        database: 'PostgreSQL 12',
        infrastructure: 'On-Premise Virtual Machines (Hyper-V)',
        repositoryUrl: 'https://github.com/enterprise-org/bioclock-legacy',
        documentationUrl: 'https://wiki.enterprise.internal/display/HR/BioClock',
        environment: 'Staging',
        status: 'Deprecated',
        criticality: 'Low',
        version: '1.4.9',
        deploymentDate: new Date('2018-05-10'),
        dependencies: 'HID Global Biometric Scanner DLLs, Legacy SQL Linked Server',
        securityNotes: 'Isolated in protected VLAN with no direct internet egress.',
        complianceRequirements: 'BIPA (Biometric Information Privacy Act)',
        notes: 'Final decommission date scheduled for end of next quarter.',
    },
    {
        systemId: 'SYS-LMS-011',
        name: 'SkillMatrix Corporate Learning Portal',
        description: 'Employee professional development portal, mandatory compliance training courses, certification exams, and skill progression matrix.',
        businessDomain: 'HR',
        domainOwner: 'Olivia Zhang',
        ownerEmail: 'olivia.zhang@enterprise.internal',
        developmentTeam: 'Talent Enablement Squad',
        technologyStack: 'React, Python FastAPI, PostgreSQL, AWS S3, CloudFront',
        programmingLanguage: 'Python / TypeScript',
        framework: 'FastAPI / React',
        database: 'PostgreSQL 15',
        infrastructure: 'AWS App Runner',
        repositoryUrl: 'https://github.com/enterprise-org/skillmatrix-lms',
        documentationUrl: 'https://wiki.enterprise.internal/display/HR/SkillMatrix',
        environment: 'Staging',
        status: 'Under Maintenance',
        criticality: 'Medium',
        version: '2.0.1-rc3',
        deploymentDate: new Date('2023-10-05'),
        dependencies: 'SCORM Cloud Player, Coursera Enterprise API, LinkedIn Learning API',
        securityNotes: 'OAuth2 authentication with company SSO.',
        complianceRequirements: 'OSHA Safety Training Requirements, Mandatory Anti-Harassment Compliance',
        notes: 'Undergoing video streaming CDN cache performance optimization.',
    },
    {
        systemId: 'SYS-SEC-012',
        name: 'Sentinel Identity & Zero-Trust Access Gateway',
        description: 'Centralized authentication broker, microservice perimeter proxy, privileged access management (PAM), and anomaly detection engine.',
        businessDomain: 'IT',
        domainOwner: 'Alexander Wright',
        ownerEmail: 'alexander.wright@enterprise.internal',
        developmentTeam: 'Cybersecurity & IAM Team',
        technologyStack: 'Go, Rust, PostgreSQL, Redis, Envoy Proxy, Kubernetes, AWS',
        programmingLanguage: 'Go / Rust',
        framework: 'Custom Envoy Extensions / Gin',
        database: 'PostgreSQL 16 / Redis Cluster',
        infrastructure: 'AWS EKS Multi-Region Cluster',
        repositoryUrl: 'https://github.com/enterprise-org/sentinel-iam-gateway',
        documentationUrl: 'https://wiki.enterprise.internal/display/SEC/Sentinel',
        environment: 'Production',
        status: 'Active',
        criticality: 'Critical',
        version: '4.8.0',
        deploymentDate: new Date('2022-01-15'),
        dependencies: 'YubiKey FIDO2 Server, HashiCorp Vault, Splunk SIEM Forwarder',
        securityNotes: 'Hardware security module (HSM) backed crypto keys. Automated IP geo-fencing and velocity checks.',
        complianceRequirements: 'FedRAMP High, NIST SP 800-53, SOC 2 Type II, ISO 27001',
        notes: 'Processes over 12 million authentication and API authorization requests per day.',
    },
    {
        systemId: 'SYS-DAT-013',
        name: 'NextGen Data Lakehouse & AI Analytics Platform',
        description: 'Unified big data aggregation pipeline, feature store, generative AI inference gateway, and executive KPI business intelligence reporting.',
        businessDomain: 'IT',
        domainOwner: 'Dr. Vikram Patel',
        ownerEmail: 'vikram.patel@enterprise.internal',
        developmentTeam: 'Data & AI Center of Excellence',
        technologyStack: 'Python, Apache Spark, Snowflake, PostgreSQL, Kubernetes, Terraform',
        programmingLanguage: 'Python / Scala / SQL',
        framework: 'FastAPI / Ray / PyTorch',
        database: 'PostgreSQL 16 / Snowflake / Iceberg',
        infrastructure: 'Hybrid Cloud AWS EKS & Snowflake',
        repositoryUrl: 'https://github.com/enterprise-org/nextgen-data-lakehouse',
        documentationUrl: 'https://wiki.enterprise.internal/display/DATA/Lakehouse',
        environment: 'Development',
        status: 'Planned',
        criticality: 'High',
        version: '0.9.0-alpha',
        deploymentDate: null,
        dependencies: 'Kafka Streaming, dbt Core, Databricks Engine, OpenSearch',
        securityNotes: 'Column-level data masking and differential privacy algorithms for confidential datasets.',
        complianceRequirements: 'GDPR Article 25 (Privacy by Design), HIPAA, CCPA',
        notes: 'Architecture blueprint approved by Architecture Review Board. Pilot release targeting Q3.',
    },
    {
        systemId: 'SYS-MKT-014',
        name: 'BrandPortal Digital Asset Distribution',
        description: 'Centralized media library for vector logos, marketing collateral, brand guidelines, photoshoot assets, and press media kits.',
        businessDomain: 'Marketing',
        domainOwner: 'Claire Dupont',
        ownerEmail: 'claire.dupont@enterprise.internal',
        developmentTeam: 'Creative Operations Tech',
        technologyStack: 'Next.js, Node.js, PostgreSQL, AWS S3, CloudFront',
        programmingLanguage: 'TypeScript',
        framework: 'Next.js 14',
        database: 'PostgreSQL 15',
        infrastructure: 'Vercel + AWS S3 / CloudFront',
        repositoryUrl: 'https://github.com/enterprise-org/brand-portal',
        documentationUrl: 'https://wiki.enterprise.internal/display/MKT/BrandPortal',
        environment: 'Production',
        status: 'Active',
        criticality: 'Low',
        version: '1.2.0',
        deploymentDate: new Date('2023-07-22'),
        dependencies: 'Adobe Creative Cloud Connector, S3 Pre-signed URLs',
        securityNotes: 'Expiring download links for high-res unreleased product photography.',
        complianceRequirements: 'Digital Millennium Copyright Act (DMCA) compliance',
        notes: 'Self-service portal for global agency partners and internal designers.',
    }
];
async function runSeed() {
    console.log('🌱 Starting Enterprise Software Registry database seed...');
    // Hash demo admin password
    const passwordHash = await bcryptjs_1.default.hash(exports.SEED_ADMIN.password, 10);
    // Upsert demo Admin User
    const adminUser = await prisma.user.upsert({
        where: { email: exports.SEED_ADMIN.email },
        update: {
            name: exports.SEED_ADMIN.name,
            passwordHash,
            role: exports.SEED_ADMIN.role,
            department: exports.SEED_ADMIN.department,
        },
        create: {
            email: exports.SEED_ADMIN.email,
            name: exports.SEED_ADMIN.name,
            passwordHash,
            role: exports.SEED_ADMIN.role,
            department: exports.SEED_ADMIN.department,
        },
    });
    console.log(`✅ Admin user seeded: ${adminUser.email} (${adminUser.name})`);
    // Seed software systems
    let createdCount = 0;
    let updatedCount = 0;
    for (const system of exports.SEED_SOFTWARE_SYSTEMS) {
        const existing = await prisma.softwareSystem.findUnique({
            where: { systemId: system.systemId },
        });
        if (existing) {
            await prisma.softwareSystem.update({
                where: { systemId: system.systemId },
                data: {
                    ...system,
                    createdBy: adminUser.id,
                },
            });
            updatedCount++;
        }
        else {
            await prisma.softwareSystem.create({
                data: {
                    ...system,
                    createdBy: adminUser.id,
                },
            });
            createdCount++;
        }
    }
    console.log(`✅ Seeded ${createdCount} new and ${updatedCount} updated software systems.`);
    console.log('🎉 Enterprise Software Registry database seeding completed successfully!');
}
if (process.argv[1] && process.argv[1].endsWith('seed.ts')) {
    runSeed()
        .catch((error) => {
        console.error('❌ Error during database seeding:', error);
        process.exit(1);
    })
        .finally(async () => {
        await prisma.$disconnect();
    });
}
